name: Pull Request Validation (Deprecated)

# ⚠️ This workflow is deprecated and kept for reference only
# All PR validation is now handled by the main CI workflow (.github/workflows/ci.yml)
# which runs a sequential pipeline to optimize resource usage:
#   1. Unit Tests & Coverage
#   2. Build Validation (Node 18, 20, 22)
#   3. CodeQL Security Analysis + PR Validation Comment
#
# This workflow is disabled to prevent duplicate runs

on:
  # Disabled - uncomment to re-enable
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches:
  #     - development
  #     - main
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-validation-deprecated:
    name: PR Validation (Use CI workflow instead)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Deprecation Notice
        run: |
          echo "⚠️ This workflow is deprecated"
          echo "Please use the main CI workflow instead: .github/workflows/ci.yml"
          echo "The CI workflow provides:"
          echo "  - Sequential pipeline for resource optimization"
          echo "  - Unit tests → Build validation → Security analysis"
          echo "  - Automatic PR comments with validation results"
