name: Merge Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # This workflow now delegates to the comprehensive CI workflow
  # The CI workflow handles linting, building, and testing across multiple Node versions
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run code:check:ci

      - name: Build all packages
        run: npm run build:all

      - name: Run tests with coverage
        run: |
          npm run test:ready
          npm run test -- --coverage

  require_successful_validation:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Ensure validation passed
        if: ${{ needs.validate.result == 'success' }}
        run: exit 0

      - name: Fail if validation failed
        if: ${{ needs.validate.result != 'success' }}
        run: exit 1
